from math import sqrt

'''
First Python attempt the second project euler problem.
"Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms."
'''
ans = 0 
ansMax = int(input(" input max "))
intAccum = 0
n = 0
strTotal = ""


def Fibin(n, ans):

	ans = int(((1 + sqrt(5)) ** n - (1 - sqrt(5))**n) / (2 ** n * sqrt(5)))
	return ans
	


while ans < ansMax:
	ans = Fibin(n, ans)
	if ans <= ansMax:
		print str(ans)
		n += 1
		if ans % 2 == 0: 
			intAccum += ans 
		
	else: 
		pass


print str(intAccum) + " end "


		


		


